# Generated by Django 5.1.3 on 2024-11-23 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sk',
            old_name='article_id',
            new_name='sk_id',
        ),
        migrations.AddField(
            model_name='sk',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
